name: Generate Snake GIF

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Snake GIF
        run: python generate-snake.py

      - name: Commit and push the snake GIF
        run: |
          git add .github/snake/github-contribution-grid-snake.svg
          git commit -m "Update Snake GIF"
          git push
